# Generated by Django 6.0.2 on 2026-03-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_complaint_complaint_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(max_length=50),
        ),
    ]