# Generated by Django 6.0.2 on 2026-03-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_created_complaint_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Waiting', 'In Waiting'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Waiting', max_length=20),
        ),
    ]