# Generated by Django 6.0.2 on 2026-04-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_created_at_notification_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaningschedule',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='cleaningschedule',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleaningschedule',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]