# Generated by Django 6.0.2 on 2026-04-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_timestamp_notification_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/images/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='complaints/videos/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Waiting', max_length=20),
        ),
    ]