# Generated by Django 6.0.2 on 2026-04-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20)),
                ('service_type', models.CharField(choices=[('Street Cleaning', 'Street Cleaning'), ('Garbage Pickup', 'Garbage Pickup'), ('Drain Cleaning', 'Drain Cleaning')], max_length=50)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
            ],
        ),
    ]
