# Generated by Django 6.0.2 on 2026-04-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_complaint_after_image_complaint_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
