# Generated by Django 6.0.2 on 2026-04-10 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_announcement_created_announcement_alert_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
