# Generated by Django 6.0.2 on 2026-04-10 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_feedback_message_feedback_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boundary', models.JSONField(help_text='GeoJSON Polygon data')),
                ('status', models.CharField(choices=[('Clean', 'Clean'), ('Moderate', 'Moderate'), ('Critical', 'Critical')], default='Clean', max_length=20)),
                ('complaint_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_zones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
