# Generated by Django 6.0.2 on 2026-04-10 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('garbage_truck', 'Garbage Truck'), ('water_tanker', 'Water Tanker'), ('service_vehicle', 'Service Vehicle'), ('sweeper', 'Road Sweeper')], default='garbage_truck', max_length=30)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('assigned_zone', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Moving', 'Moving'), ('Idle', 'Idle'), ('Offline', 'Offline')], default='Moving', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('base_lat', models.FloatField(default=32.5736)),
                ('base_lng', models.FloatField(default=74.079)),
                ('sim_phase', models.FloatField(default=0.0, help_text='Simulation phase offset for GPS trajectory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
