# Generated by Django 6.0.2 on 2026-04-11 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_servicecategory_servicepaymentsetting_servicebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(help_text='e.g., Eid-ul-Fitr', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('special_plan', models.TextField(blank=True, help_text='Optional: Post a special waste management plan')),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(help_text='e.g., Fawara Chowk', max_length=150)),
                ('union_council', models.CharField(help_text='e.g., Model Town', max_length=150)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-weekly', 'Bi-weekly')], default='Daily', max_length=20)),
                ('day_of_week', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipal_schedules', to='accounts.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150)),
                ('title', models.CharField(help_text='e.g., Pipe Burst Alert', max_length=200)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.servicecategory')),
            ],
        ),
    ]
