# Generated by Django 6.0.2 on 2026-04-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_holidayconfig_municipalserviceschedule_schedulealert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_range', models.CharField(help_text="e.g., '0 - 5 km', '5 - 10 km'", max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('urgent_price', models.DecimalField(decimal_places=2, default=100.0, help_text='Price when priority is Urgent', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
