# Generated by Django 6.0.2 on 2026-04-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_complaintpricingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='fee_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.complaintpricingconfig'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='holidayconfig',
            name='adjustment_description',
            field=models.CharField(blank=True, help_text='e.g., Festive Season Discount', max_length=200),
        ),
        migrations.AddField(
            model_name='holidayconfig',
            name='is_pricing_active',
            field=models.BooleanField(default=False, help_text='Enable price adjustments for this day'),
        ),
        migrations.AddField(
            model_name='holidayconfig',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='e.g., 0.8 for 20% off, 1.2 for 20% surcharge', max_digits=4),
        ),
    ]
