# Generated by Django 6.0.2 on 2026-04-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_complaint_fee_tier_complaint_final_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='duties',
            field=models.CharField(blank=True, help_text='e.g., Sweeper, Garbage Pickup', max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='duty_time',
            field=models.CharField(blank=True, help_text='e.g., Morning (8AM - 4PM)', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
