# Generated by Django 6.0.2 on 2026-04-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='payfast_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='payfast_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
