# Generated by Django 6.0.2 on 2026-04-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_wallet_payfast_email_wallet_payfast_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_linked',
            field=models.BooleanField(default=False),
        ),
    ]
