# Generated by Django 6.0.2 on 2026-04-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_wallet_is_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
