# Generated by Django 6.0.2 on 2026-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_servicebooking_advance_fee_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayconfig',
            name='coverage_tags',
            field=models.TextField(blank=True, help_text='e.g., Active During Holidays Only, Limited-Time Service'),
        ),
        migrations.AddField(
            model_name='holidayconfig',
            name='holiday_type',
            field=models.CharField(choices=[('Eid', 'Eid (Moon Icon)'), ('Public', 'Public Holiday (Flag)'), ('Festive', 'Festive (Gift)'), ('Emergency', 'Emergency (Alert)')], default='Public', max_length=20),
        ),
        migrations.AddField(
            model_name='holidayconfig',
            name='service_status',
            field=models.CharField(choices=[('Available Now', '✅ Available Now'), ('Limited Staff', '⚠️ Limited Staff'), ('Fully Booked', '❌ Fully Booked')], default='Available Now', max_length=30),
        ),
        migrations.AddField(
            model_name='holidayconfig',
            name='special_services',
            field=models.TextField(blank=True, help_text='Comma-separated: Emergency handling, Road cleaning, etc.'),
        ),
    ]
