# Generated by Django 6.0.2 on 2026-04-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_holidayconfig_coverage_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayconfig',
            name='zones_covered',
            field=models.TextField(blank=True, help_text='Comma-separated: Zone A, Zone B, etc.'),
        ),
    ]
