# Generated by Django 6.0.2 on 2026-04-23 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='accounts.vehicle'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='tracking_status',
            field=models.CharField(choices=[('Station', 'At Station'), ('Dispatched', 'Dispatched / En Route'), ('Arrived', 'Arrived at Location'), ('Returning', 'Returning to Base'), ('Completed', 'Task Completed')], default='Station', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='tracking_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
