# Generated by Django 6.0.2 on 2026-04-23 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_complaint_assigned_vehicle_complaint_tracking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_vehicle',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='tracking_status',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='tracking_updated_at',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicle', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_vehicle', to='accounts.complaint'),
        ),
    ]
