# Generated by Django 6.0.2 on 2026-04-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_staff_assigned_zone_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='source_name',
            field=models.CharField(default='Main Depot', help_text="Starting point name, e.g., 'West Garage'", max_length=100),
        ),
    ]
