# Generated by Django 6.0.2 on 2026-04-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_vehicle_latitude_vehicle_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Official completion proof (Admin)', null=True, upload_to='complaints/proof_images/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='proof_video',
            field=models.FileField(blank=True, help_text='Official completion proof (Admin)', null=True, upload_to='complaints/proof_videos/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Proof of completion by staff', null=True, upload_to='complaints/after_images/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Active', 'Active / On Duty'), ('Idle', 'Idle / Waiting'), ('In Transit', 'In Transit'), ('Arrived', 'Arrived'), ('Work in Progress', 'Work in Progress'), ('Completed', 'Completed'), ('Offline', 'Offline'), ('Out of Service', 'Out of Service'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='Moving', max_length=20),
        ),
    ]
