# Generated by Django 6.0.2 on 2026-05-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_complaint_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='payfast_id',
            new_name='stripe_account_id',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='payfast_email',
            new_name='stripe_email',
        ),
        migrations.AlterField(
            model_name='servicepaymentsetting',
            name='gateway_name',
            field=models.CharField(default='Stripe', max_length=100),
        ),
    ]
