# Generated by Django 6.0.2 on 2026-05-08 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_staff_address_staff_certifications_staff_cnic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='age',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department_zone',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='duties',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='duty_time',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='key_responsibilities',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='license_category',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='license_expiry',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='management_experience',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='operational_qualification',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='operator_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='shift_assignment',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_supervised',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='supervisor_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='supervisory_certification',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='vehicle_assignment',
        ),
        migrations.CreateModel(
            name='DriverDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('license_category', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_assignment', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_detail', to='accounts.staff')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(blank=True, max_length=50, null=True)),
                ('shift_assignment', models.CharField(blank=True, max_length=50, null=True)),
                ('operational_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_detail', to='accounts.staff')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('department_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('management_experience', models.IntegerField(blank=True, null=True)),
                ('staff_supervised', models.IntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisory_certification', models.CharField(blank=True, max_length=100, null=True)),
                ('key_responsibilities', models.TextField(blank=True, null=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_detail', to='accounts.staff')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('duties', models.CharField(blank=True, max_length=200)),
                ('duty_time', models.CharField(blank=True, max_length=100)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_detail', to='accounts.staff')),
            ],
        ),
    ]
