# Generated by Django 6.0.2 on 2026-05-08 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_photogallerycategory_photoproject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='image', help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color code for tags', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
            },
        ),
        migrations.RemoveField(
            model_name='photoproject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='photoproject',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='photoproject',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='photoproject',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='photoprojectcomment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='photoprojectcomment',
            name='user',
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Resolved', 'Resolved'), ('In Progress', 'In Progress')], default='Completed', max_length=20)),
                ('before_image', models.ImageField(upload_to='gallery/before/')),
                ('after_image', models.ImageField(upload_to='gallery/after/')),
                ('likes_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('allow_likes', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.gallerycategory')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='accounts.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='accounts.galleryitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('gallery_item', 'user', 'ip_address')},
            },
        ),
        migrations.DeleteModel(
            name='PhotoGalleryCategory',
        ),
        migrations.DeleteModel(
            name='PhotoProject',
        ),
        migrations.DeleteModel(
            name='PhotoProjectComment',
        ),
    ]
