# Generated by Django 6.0.2 on 2026-05-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_gallerycategory_remove_photoproject_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='assign_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='estimating_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
