# Generated by Django 6.0.2 on 2026-05-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_vehicle_assign_date_vehicle_estimating_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipalserviceschedule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('All Day', 'All Day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='municipalserviceschedule',
            name='union_council',
            field=models.CharField(blank=True, help_text='e.g., Model Town', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Garbage issue', 'Garbage truck'), ('Drainage issue', 'Drain cleaner truck'), ('Street light issue', 'Lift truck'), ('Water issue', 'Water tanker'), ('Street cleaning', 'Road cleaning truck')], default='garbage_truck', max_length=30),
        ),
    ]
