# Generated by Django 6.0.2 on 2026-05-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_municipalserviceschedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='approaching_time',
            field=models.CharField(blank=True, help_text='e.g. 8-12m', max_length=50, null=True),
        ),
    ]
