# Generated by Django 6.0.2 on 2026-05-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_vehicle_approaching_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='assign_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
