# Generated by Django 6.0.2 on 2026-05-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Actionable link for the notification', max_length=255, null=True),
        ),
    ]
