# Generated by Django 6.0.2 on 2026-05-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='helpline_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('critical', '🔴 Critical'), ('high', '🟠 High'), ('medium', '🟡 Medium'), ('low', '🟢 Low')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='response_team_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('delayed', 'Delayed'), ('closed', 'Closed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='visibility_duration',
            field=models.CharField(choices=[('24h', 'Show for 24 hours'), ('until_resolved', 'Show until resolved'), ('permanent', 'Permanent notice')], default='permanent', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='alert_type',
            field=models.CharField(blank=True, default='info', max_length=20),
        ),
    ]
