# Generated by Django 6.0.2 on 2026-05-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_remove_announcement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetail',
            name='plate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
